package compose

import (
	"fmt"
	"strings"

	"github.com/projectchimera/chimera/internal/scanner"
)

// GenerateDockerfile produces a Dockerfile for the detected primary language.
func GenerateDockerfile(lang scanner.Language) string {
	switch strings.ToLower(lang.Name) {
	case "node.js", "nodejs", "javascript", "typescript":
		return dockerfileNode(lang.Version)
	case "python":
		return dockerfilePython(lang.Version)
	case "go", "golang":
		return dockerfileGo(lang.Version)
	default:
		return dockerfileNode("18") // fallback
	}
}

func dockerfileNode(version string) string {
	if version == "" {
		version = "18"
	}
	// Only use major version for the image tag
	major := strings.Split(version, ".")[0]
	return fmt.Sprintf(`# Generated by Chimera
FROM node:%s-alpine

WORKDIR /app

# Install dependencies first for better caching
COPY package*.json ./
RUN npm ci --only=production

# Copy application source
COPY . .

EXPOSE 3000

CMD ["node", "."]
`, major)
}

func dockerfilePython(version string) string {
	if version == "" {
		version = "3.11"
	}
	return fmt.Sprintf(`# Generated by Chimera
FROM python:%s-slim

WORKDIR /app

# Install dependencies first for better caching
COPY requirements.txt* pyproject.toml* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || \
    pip install --no-cache-dir . 2>/dev/null || true

# Copy application source
COPY . .

EXPOSE 8000

CMD ["python", "-m", "app"]
`, version)
}

func dockerfileGo(version string) string {
	if version == "" {
		version = "1.21"
	}
	return fmt.Sprintf(`# Generated by Chimera — multi-stage build
FROM golang:%s-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o app .

# Final stage
FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /build/app .

EXPOSE 8080

CMD ["./app"]
`, version)
}
