package compose

import (
	"fmt"
	"strings"

	"github.com/projectchimera/chimera/internal/scanner"
)

// envDefaults maps infrastructure types to their default connection URL variable and value template.
var envDefaults = map[string]struct {
	VarName  string
	Template string // %s is replaced with projectName
}{
	"postgresql":    {"DATABASE_URL", "postgresql://postgres:postgres@postgres:5432/%s"},
	"mysql":         {"DATABASE_URL", "mysql://root:mysql@mysql:3306/%s"},
	"mongodb":       {"MONGODB_URL", "mongodb://mongodb:27017/%s"},
	"redis":         {"REDIS_URL", "redis://redis:6379/0"},
	"rabbitmq":      {"RABBITMQ_URL", "amqp://guest:guest@rabbitmq:5672/"},
	"elasticsearch": {"ELASTICSEARCH_URL", "http://elasticsearch:9200"},
}

// GenerateEnvFile produces a .env.example file with intelligently pre-populated defaults.
func GenerateEnvFile(projectName string, result *scanner.ScanResult) string {
	var b strings.Builder
	b.WriteString("# Generated by Chimera\n")
	b.WriteString("# Copy this file to .env and fill in any missing values\n\n")

	// Pre-populate infra connection URLs
	populated := make(map[string]bool)
	for _, infra := range result.Infrastructure {
		if def, ok := envDefaults[infra.Type]; ok {
			var val string
			if strings.Contains(def.Template, "%s") {
				val = fmt.Sprintf(def.Template, projectName)
			} else {
				val = def.Template
			}
			b.WriteString(fmt.Sprintf("%s=%s\n", def.VarName, val))
			populated[def.VarName] = true
		}
	}

	if len(result.Infrastructure) > 0 {
		b.WriteString("\n")
	}

	// Add all detected env vars that weren't already populated
	if len(result.EnvVars) > 0 {
		b.WriteString("# Application environment variables\n")
		for _, varName := range result.EnvVars {
			if populated[varName] {
				continue
			}
			b.WriteString(fmt.Sprintf("%s= # set this value\n", varName))
		}
	}

	return b.String()
}
