// Package proxy handles Caddy reverse proxy and /etc/hosts management.
package proxy

import (
	"bufio"
	"fmt"
	"net/url"
	"os"
	"regexp"
	"runtime"
	"strings"
)

const chimeraTag = "# chimera-managed"

// DeriveLocalDomain derives a .local domain from a repo URL.
// e.g. "github.com/acme/My_Service" → "my-service.local"
func DeriveLocalDomain(repoURL string) string {
	name := ProjectName(repoURL)
	if name == "" {
		return "chimera.local"
	}
	return name + ".local"
}

// ProjectName extracts a clean project name from a repo URL.
func ProjectName(repoURL string) string {
	var raw string

	if strings.HasPrefix(repoURL, "git@") {
		parts := strings.Split(repoURL, ":")
		if len(parts) == 2 {
			raw = parts[1]
		}
	} else {
		parsed, err := url.Parse(repoURL)
		if err != nil || parsed.Path == "" {
			return "chimera"
		}
		raw = parsed.Path
	}

	raw = strings.TrimSuffix(raw, ".git")
	raw = strings.TrimPrefix(raw, "/")

	// Take only the last segment (repo name, not org)
	parts := strings.Split(raw, "/")
	if len(parts) > 0 {
		raw = parts[len(parts)-1]
	}

	// Clean: lowercase, replace _ and spaces with -, strip non-alnum except -
	raw = strings.ToLower(raw)
	raw = strings.ReplaceAll(raw, "_", "-")
	raw = strings.ReplaceAll(raw, " ", "-")
	re := regexp.MustCompile(`[^a-z0-9-]`)
	raw = re.ReplaceAllString(raw, "")
	raw = strings.Trim(raw, "-")

	if raw == "" {
		return "chimera"
	}
	return raw
}

// GenerateCaddyfile returns a minimal Caddyfile for reverse proxying.
func GenerateCaddyfile(domain string, appPort int) string {
	return fmt.Sprintf(`# Generated by Chimera
%s {
  reverse_proxy app:%d
}
`, domain, appPort)
}

// CaddyComposeSnippet returns the Caddy service YAML to be appended to docker-compose.yml.
func CaddyComposeSnippet(projectName, netName string) string {
	snippet := "\n" +
		"  caddy:\n" +
		"    image: caddy:2.7-alpine\n" +
		"    ports:\n" +
		"      - \"80:80\"\n" +
		"      - \"443:443\"\n" +
		"    volumes:\n" +
		"      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n"

	if netName != "" {
		snippet += "    networks:\n" +
			fmt.Sprintf("      - %s\n", netName)
	}

	snippet += "    restart: unless-stopped\n" +
		"    labels:\n" +
		fmt.Sprintf("      com.chimera.project: \"%s\"\n", projectName)

	return snippet
}

// HostsFilePath returns the platform-correct path to the hosts file.
func HostsFilePath() string {
	if runtime.GOOS == "windows" {
		return `C:\Windows\System32\drivers\etc\hosts`
	}
	return "/etc/hosts"
}

// EntryExists checks if a domain entry already exists in the hosts file.
func EntryExists(domain string) (bool, error) {
	return entryExistsInFile(HostsFilePath(), domain)
}

func entryExistsInFile(path, domain string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, fmt.Errorf("proxy: cannot read hosts file: %w", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.Contains(line, domain) && strings.Contains(line, chimeraTag) {
			return true, nil
		}
	}
	return false, scanner.Err()
}

// AddEntry appends a chimera-managed entry to the hosts file. Idempotent.
func AddEntry(domain string, projectName string) error {
	return addEntryToFile(HostsFilePath(), domain, projectName)
}

func addEntryToFile(path, domain, projectName string) error {
	// Check if already exists
	exists, err := entryExistsInFile(path, domain)
	if err != nil {
		return err
	}
	if exists {
		return nil // idempotent
	}

	entry := fmt.Sprintf("127.0.0.1  %s  %s:%s\n", domain, chimeraTag, projectName)
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		// Permission denied — suggest sudo
		return fmt.Errorf("proxy: cannot write to %s (try running with sudo): %w", path, err)
	}
	defer f.Close()

	_, err = f.WriteString(entry)
	if err != nil {
		return fmt.Errorf("proxy: failed to write hosts entry: %w", err)
	}
	return nil
}

// RemoveEntry removes all chimera-managed entries for a given project. Idempotent.
func RemoveEntry(projectName string) error {
	return removeEntryFromFile(HostsFilePath(), projectName)
}

func removeEntryFromFile(path, projectName string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("proxy: cannot read hosts file: %w", err)
	}

	tag := fmt.Sprintf("%s:%s", chimeraTag, projectName)
	lines := strings.Split(string(content), "\n")
	var kept []string
	changed := false

	for _, line := range lines {
		if strings.Contains(line, tag) {
			changed = true
			continue
		}
		kept = append(kept, line)
	}

	if !changed {
		return nil // nothing to remove, idempotent
	}

	return os.WriteFile(path, []byte(strings.Join(kept, "\n")), 0644)
}
