package compose

import (
	"fmt"
	"strings"

	"github.com/projectchimera/chimera/internal/scanner"
)

// GenerateDockerfile produces a Dockerfile for the detected primary language.
func GenerateDockerfile(result *scanner.ScanResult) string {
	if len(result.Languages) == 0 {
		return dockerfileNode("18", nil) // fallback
	}

	lang := result.Languages[0]
	var fw *scanner.FrameworkInfo
	for _, f := range result.Frameworks {
		// Try to match based on category or implicit language from start cmd
		if strings.ToLower(lang.Name) == "python" && (strings.Contains(f.InstallCmd, "pip") || strings.Contains(f.StartCmd, "python") || strings.Contains(f.StartCmd, "gunicorn") || strings.Contains(f.StartCmd, "uvicorn") || strings.Contains(f.StartCmd, "flask") || strings.Contains(f.StartCmd, "streamlit")) {
			fw = &f
			break
		} else if (strings.ToLower(lang.Name) == "node.js" || strings.ToLower(lang.Name) == "nodejs") && (strings.Contains(f.InstallCmd, "npm") || strings.Contains(f.InstallCmd, "yarn") || strings.Contains(f.InstallCmd, "pnpm")) {
			fw = &f
			break
		} else if strings.ToLower(lang.Name) == "go" && strings.Contains(f.InstallCmd, "go ") {
			fw = &f
			break
		}
	}

	switch strings.ToLower(lang.Name) {
	case "node.js", "nodejs", "javascript", "typescript":
		return dockerfileNode(lang.Version, fw)
	case "python":
		return dockerfilePython(lang.Version, fw)
	case "go", "golang":
		return dockerfileGo(lang.Version, fw)
	default:
		return dockerfileNode("18", fw) // fallback
	}
}

func dockerfileNode(version string, fw *scanner.FrameworkInfo) string {
	if version == "" {
		version = "18"
	}
	major := strings.Split(version, ".")[0]
	
	installCmd := "RUN npm ci --only=production"
	startCmd := "CMD [\"npm\", \"start\"]"
	buildCmd := ""
	
	if fw != nil {
		if fw.InstallCmd != "" {
			installCmd = "RUN " + fw.InstallCmd
		}
		if fw.StartCmd != "" {
			parts := strings.Split(fw.StartCmd, " ")
			startCmd = fmt.Sprintf("CMD [\"%s\"]", strings.Join(parts, "\", \""))
		}
		if fw.BuildCmd != "" {
			buildCmd = "RUN " + fw.BuildCmd + "\n"
		}
	}

	return fmt.Sprintf(`# Generated by Chimera
FROM node:%s-alpine

WORKDIR /app

# Install dependencies first for better caching
COPY package*.json ./
%s

# Copy application source
COPY . .

%sEXPOSE 3000

%s
`, major, installCmd, buildCmd, startCmd)
}

func dockerfilePython(version string, fw *scanner.FrameworkInfo) string {
	if version == "" {
		version = "3.11"
	}
	
	installCmd := "RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || \\\n    pip install --no-cache-dir . 2>/dev/null || true"
	startCmd := "CMD [\"python\", \"main.py\"]"
	
	if fw != nil {
		if fw.InstallCmd != "" {
			installCmd = "RUN " + fw.InstallCmd
		}
		if fw.StartCmd != "" {
			parts := strings.Split(fw.StartCmd, " ")
			startCmd = fmt.Sprintf("CMD [\"%s\"]", strings.Join(parts, "\", \""))
		}
	}

	return fmt.Sprintf(`# Generated by Chimera
FROM python:%s-slim

WORKDIR /app

# Install dependencies first for better caching
COPY requirements.txt* pyproject.toml* Pipfile* ./
%s

# Copy application source
COPY . .

EXPOSE 8000

%s
`, version, installCmd, startCmd)
}

func dockerfileGo(version string, fw *scanner.FrameworkInfo) string {
	if version == "" {
		version = "1.21"
	}
	
	buildCmd := "RUN CGO_ENABLED=0 GOOS=linux go build -ldflags=\"-s -w\" -o app ."
	startCmd := "CMD [\"./app\"]"
	
	if fw != nil {
		if fw.BuildCmd != "" {
			// Ensure it still builds an executable named "app"
			if !strings.Contains(fw.BuildCmd, "-o ") {
				buildCmd = "RUN " + fw.BuildCmd
			} else {
				buildCmd = "RUN CGO_ENABLED=0 GOOS=linux " + fw.BuildCmd
			}
		}
	}

	return fmt.Sprintf(`# Generated by Chimera — multi-stage build
FROM golang:%s-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
%s

# Final stage
FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /build/app .

EXPOSE 8080

%s
`, version, buildCmd, startCmd)
}
