package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Config holds the Chimera configuration
type Config struct {
	LLMProvider string
	LLMModel    string
	LLMAPIKey   string
	GitHubPAT   string
}

// ChimeraHome returns the platform-specific chimera home directory
func ChimeraHome() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get user home directory: %w", err)
	}
	return filepath.Join(home, ".chimera"), nil
}

// ReposDir returns the repos directory
func ReposDir() (string, error) {
	home, err := ChimeraHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, "repos"), nil
}

// ConfigPath returns the path to the config file
func ConfigPath() (string, error) {
	home, err := ChimeraHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".chimera.env"), nil
}

// Load reads the configuration from ~/.chimera/.chimera.env
func Load() (*Config, error) {
	configPath, err := ConfigPath()
	if err != nil {
		return nil, err
	}

	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return nil, fmt.Errorf("config file not found")
	}

	vars := readEnvFile(configPath)

	config := &Config{
		LLMProvider: vars["CHIMERA_LLM_PROVIDER"],
		LLMModel:    vars["CHIMERA_LLM_MODEL"],
		LLMAPIKey:   vars["CHIMERA_LLM_API_KEY"],
		GitHubPAT:   vars["CHIMERA_GITHUB_PAT"],
	}

	// Validate required fields
	if config.LLMProvider == "" || config.LLMModel == "" || config.LLMAPIKey == "" {
		return nil, fmt.Errorf("incomplete configuration")
	}

	return config, nil
}

// Save writes the configuration to ~/.chimera/.chimera.env
func Save(config *Config) error {
	home, err := ChimeraHome()
	if err != nil {
		return err
	}

	// Create chimera home directory if it doesn't exist
	if err := os.MkdirAll(home, 0755); err != nil {
		return fmt.Errorf("failed to create chimera home: %w", err)
	}

	configPath := filepath.Join(home, ".chimera.env")

	var content strings.Builder
	content.WriteString("# Chimera configuration — generated by chimera setup\n")
	content.WriteString("# Do not edit manually unless you know what you are doing\n\n")
	content.WriteString(fmt.Sprintf("CHIMERA_LLM_PROVIDER=%s\n", config.LLMProvider))
	content.WriteString(fmt.Sprintf("CHIMERA_LLM_MODEL=%s\n", config.LLMModel))
	content.WriteString(fmt.Sprintf("CHIMERA_LLM_API_KEY=%s\n", config.LLMAPIKey))
	if config.GitHubPAT != "" {
		content.WriteString(fmt.Sprintf("CHIMERA_GITHUB_PAT=%s\n", config.GitHubPAT))
	}

	// Write with 0600 permissions (owner read/write only)
	if err := os.WriteFile(configPath, []byte(content.String()), 0600); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

// readEnvFile reads a .env-style file and returns key-value pairs
func readEnvFile(path string) map[string]string {
	vars := make(map[string]string)

	f, err := os.Open(path)
	if err != nil {
		return vars
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip comments and empty lines
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Parse KEY=VALUE
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Remove surrounding quotes
		value = strings.Trim(value, `"'`)

		if key != "" && value != "" {
			vars[key] = value
		}
	}

	return vars
}
