package generator

import (
	"fmt"
	"sort"
	"strings"

	"chimera/internal/detector"
)

// renderCompose generates docker-compose.yml. The compose file lives at
// <repo>/<outputSubdir>/docker-compose.yml — every path is relative to that
// location so the user can run `docker compose -f <outputSubdir>/docker-compose.yml up`
// from the repo root with no further edits.
func renderCompose(services []detector.Service, repoName, outputSubdir string) string {
	if outputSubdir == "" {
		outputSubdir = "chimera-outputs"
	}
	var b strings.Builder
	projectName := safeProjectName(repoName)
	netName := projectName + "-net"

	b.WriteString("# Generated by Chimera. Run from repo root:\n")
	b.WriteString(fmt.Sprintf("#   docker compose -f %s/docker-compose.yml up\n\n", outputSubdir))
	b.WriteString("services:\n")

	usedPorts := map[int]bool{}
	for _, svc := range services {
		port := svc.Port
		if port == 0 {
			port = 3000
		}
		hostPort := port
		for usedPorts[hostPort] {
			hostPort++
		}
		usedPorts[hostPort] = true

		serviceName := safeServiceName(svc.ID)
		context := ".."
		dockerfile := fmt.Sprintf("%s/Dockerfile.%s", outputSubdir, svc.ID)
		envFile := fmt.Sprintf("env-vars/%s/.env.example", svc.ID)

		fmt.Fprintf(&b, "  %s:\n", serviceName)
		fmt.Fprintf(&b, "    build:\n")
		fmt.Fprintf(&b, "      context: %s\n", context)
		fmt.Fprintf(&b, "      dockerfile: %s\n", dockerfile)
		fmt.Fprintf(&b, "    container_name: %s-%s\n", projectName, serviceName)
		fmt.Fprintf(&b, "    ports:\n")
		fmt.Fprintf(&b, "      - \"%d:%d\"\n", hostPort, port)
		fmt.Fprintf(&b, "    env_file:\n")
		fmt.Fprintf(&b, "      - %s\n", envFile)
		fmt.Fprintf(&b, "    restart: unless-stopped\n")
		fmt.Fprintf(&b, "    networks:\n")
		fmt.Fprintf(&b, "      - %s\n\n", netName)
	}

	b.WriteString("networks:\n")
	fmt.Fprintf(&b, "  %s:\n", netName)
	b.WriteString("    driver: bridge\n")

	return b.String()
}

func safeServiceName(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, "_", "-")
	return s
}

func safeProjectName(name string) string {
	name = strings.ToLower(name)
	var out strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out.WriteRune(r)
		case r == '-', r == '_':
			out.WriteRune(r)
		default:
			out.WriteRune('-')
		}
	}
	if out.Len() == 0 {
		return "chimera"
	}
	return out.String()
}

func safeNetworkName(name string) string { // retained for backwards compat in tests
	return safeProjectName(name) + "-net"
}

// SortedFilenames returns deterministic file ordering for output writers.
func SortedFilenames(files map[string]string) []string {
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}
